feat: anaysis script about class & bbox distribution
DeepBaksuVision/seongnam-innovation-hackathon pull request #11
Opened 2019-11-25 17:32 UTC by ssaru

Resolves: #3

2019-11-26 12:37 UTC, visionNoob requested changes
코드가 전체적으로 아주 깔끔하네요. 
PEP8 한번 돌려보면 좋을 것 같습니다.

2019-11-26 12:37 UTC, visionNoob commented on script/bbox_class_distribution.py
> +    for i, row in enumerate(tqdm(csvreader, total=numline)):
i 말고 idx 는 어떠신가요

2019-11-26 12:37 UTC, visionNoob commented on script/bbox_class_distribution.py
> +        cls = str(row[3])
cls는 python 에서 미리 정의된 변수라 안쓰는게 좋을 것 같습니다. 
(https://www.python.org/dev/peps/pep-0008/#function-and-method-arguments)

2019-11-26 12:37 UTC, visionNoob commented on script/bbox_class_distribution.py
> +annotations = list()
annotations = [] 이랑 
anootations = list() 이랑 어떤 차이인가요?

2019-11-26 12:37 UTC, visionNoob commented on utils/detection_annotations.py
> +        self.CLASS: str = str(object_info["class"])
맴버변수들이 대문자인 이유는 무엇인가여?

2019-11-26 12:37 UTC, visionNoob commented on utils/detection_annotations.py
> +    def __init__(self,
여기는 한 줄로 해도 될 것 같습니다.

2019-11-26 12:37 UTC, visionNoob commented on utils/bbox_distribution.py
> +        self.classes, self.class_frequency = self._collect_classes_and_frequency(anno)
classes 는 리스트로 받는게어떨까요? 
데이터셋이 달라지면 클래스 순서가 섞일 것 같아요

2019-11-26 12:37 UTC, visionNoob commented on utils/bbox_distribution.py
> +        for cls in classes:
여기에서도 cls 변수명은 수정하는게 좋을 것 같습니다

2019-11-26 12:37 UTC, visionNoob commented on utils/bbox_distribution.py
> +    def show_bbox_distribution(self, integrated: bool = False, savefig: bool = True) -> None:
integrated 옵션이 어떤 옵션인지 파라미터 값만 봐서는 직관적으로 이해가 잘 안갔습니다.. 
더 좋은 변수명이 있을까요?

2019-11-26 12:37 UTC, visionNoob commented on utils/bbox_distribution.py
> +    def show_bbox_distribution(self, integrated: bool = False, savefig: bool = True) -> None:
savefig는 직관적으로 이해가 가지만 함수가 아닌 변수명이 동사로 시작하는게 조금 마음에 걸립니다..

2019-11-26 12:37 UTC, ssaru commented on script/bbox_class_distribution.py
> +annotations = list()
큰 차이 없는 것으로 알고 있습니다! ㅎㅎ

2019-11-26 12:38 UTC, ssaru commented on script/bbox_class_distribution.py
> +        cls = str(row[3])
오! 감사합니다. 수정하겠습니다.

2019-11-26 12:38 UTC, ssaru commented on script/bbox_class_distribution.py
> +    for i, row in enumerate(tqdm(csvreader, total=numline)):
좋습니다!

2019-11-26 12:39 UTC, ssaru commented on utils/detection_annotations.py
> +        self.CLASS: str = str(object_info["class"])
큰 이유는 없습니다.
Detectron2에 configuration쪽 클래스들의 파라미터값들은 모두 대문자 처리를해서 그와 유사하게 만들어봤습니다.

실은 python에 안맞는 컨벤션이라 변경해도 무방합니다.
그렇게 할까요?

2019-11-26 12:39 UTC, ssaru commented on utils/bbox_distribution.py
> +        for cls in classes:
네넵!

2019-11-26 12:41 UTC, ssaru commented on utils/detection_annotations.py
> +    def __init__(self,
파라미터 말씀하시는 것이군요! 알겠습니다.

2019-11-26 12:43 UTC, ssaru commented on utils/bbox_distribution.py
> +        self.classes, self.class_frequency = self._collect_classes_and_frequency(anno)
네네! 순서가 섞일 것 같아서 list로 리턴을 하게 짰는데... 혹시 리턴이 다른 타입으로 나오나요?

2019-11-26 12:43 UTC, ssaru commented on utils/bbox_distribution.py
> +    def show_bbox_distribution(self, integrated: bool = False, savefig: bool = True) -> None:
`merged`도 있을 것 같은데, 아직 생각이 잘 안나네요! 
다른 분들의 의견을 기다려보겠습니다.

2019-11-26 12:44 UTC, ssaru commented on utils/bbox_distribution.py
> +    def show_bbox_distribution(self, integrated: bool = False, savefig: bool = True) -> None:
네네 이 부분은 `matplotlib`의 `plt.savefig`.... 함수군요!
`is_save` 어떠십니까?

2019-11-26 13:31 UTC, RRoundTable commented on utils/__init__.py
> +from utils.detection_annotations import *
어떤 모듈을 사용하는지 명시해주면 더 좋을 거 같습니다.

2019-11-26 14:28 UTC, pep8speaks commented
Hello @ssaru! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`script/bbox_class_distribution.py`](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/script/bbox_class_distribution.py):

> [Line 29:9](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/script/bbox_class_distribution.py#L29): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 34:39](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/script/bbox_class_distribution.py#L34): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 35:39](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/script/bbox_class_distribution.py#L35): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 36:39](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/script/bbox_class_distribution.py#L36): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 37:39](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/script/bbox_class_distribution.py#L37): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 45:1](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/script/bbox_class_distribution.py#L45): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

* In the file [`utils/__init__.py`](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils/__init__.py):

> [Line 2:61](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils/__init__.py#L2): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`utils/bbox_distribution.py`](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils/bbox_distribution.py):

> [Line 17:80](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils/bbox_distribution.py#L17): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 21:80](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils/bbox_distribution.py#L21): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 48:80](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils/bbox_distribution.py#L48): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (106 > 79 characters)
> [Line 55:51](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils/bbox_distribution.py#L55): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 60:80](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils/bbox_distribution.py#L60): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (95 > 79 characters)
> [Line 61:80](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils/bbox_distribution.py#L61): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (96 > 79 characters)
> [Line 62:80](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils/bbox_distribution.py#L62): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 63:80](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils/bbox_distribution.py#L63): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 64:80](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils/bbox_distribution.py#L64): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 65:80](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils/bbox_distribution.py#L65): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 90:80](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils/bbox_distribution.py#L90): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (93 > 79 characters)
> [Line 95:80](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils/bbox_distribution.py#L95): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 96:80](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils/bbox_distribution.py#L96): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 108:80](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils/bbox_distribution.py#L108): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)
> [Line 113:80](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils/bbox_distribution.py#L113): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 186:80](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils/bbox_distribution.py#L186): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (176 > 79 characters)

* In the file [`utils/detection_annotations.py`](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils/detection_annotations.py):

> [Line 39:80](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils/detection_annotations.py#L39): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)
> [Line 39:86](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils/detection_annotations.py#L39): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 42:80](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils/detection_annotations.py#L42): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 60:80](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils/detection_annotations.py#L60): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 61:80](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils/detection_annotations.py#L61): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 68:23](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils/detection_annotations.py#L68): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 69:23](https://github.com/DeepBaksuVision/seongnam-innovation-hackathon/blob/5fb3772e31ae791795dd3602ecb817271be2a95b/utils [...]

2019-11-26 15:00 UTC, visionNoob requested changes

2019-11-26 15:00 UTC, visionNoob commented on script/bbox_class_distribution.py
> -anno_analyzer.show_bbox_distribution(integrated=True, savefig=False)
each_classes typo 있습니다 :D
each_classes 가 True이면 각 클래스별로 보여주는건가요?

2019-11-26 15:01 UTC, visionNoob commented on utils/bbox_distribution.py
> +    def show_bbox_distribution(self, integrated: bool = False, savefig: bool = True) -> None:
좋습니당

2019-11-26 17:22 UTC, ssaru commented on script/bbox_class_distribution.py
> -anno_analyzer.show_bbox_distribution(integrated=True, savefig=False)
오! 감사합니다. 확인해서 수정하겠습니다.

2019-11-27 00:18 UTC, visionNoob approved these changes
excellent! :D

2019-11-27 04:11 UTC, RRoundTable commented on utils/__init__.py
> +from utils.detection_annotations import DetectionAnnotations
감사합니다!

2019-11-27 04:13 UTC, RRoundTable commented on utils/detection_annotations.py
> +        self.CLASS: str = str(object_info["class"])
저는 안바꿔도 될 꺼 같습니다!

2019-11-27 05:54 UTC, merged